spring:
  dubbo:
    application:
      id: market-consumer
      name: market-consumer
    registry:
      address: zookeeper://localhost:2181
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/c2c?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: xl199914
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
# token
token:
  privateKey: 'xllx'
  yangToken: 1000
  oldToken: 3000
server:
  port: 8180